[package]
name = "jiff-chrono-conversions-example-basic"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
chrono-tz = { version = "0.10.4", default-features = false }
jiff = "0.2"
jiff-chrono-conversions = { path = "../..", features = [
  "chrono-04",
  "chrono-tz-010",
  "jiff-02"
] }
